[package]
name = "restake-me"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.5"
borsh-derive = "1.5.5"
solana-program = "~2.1"

[dev-dependencies]
solana-sdk = "~2.1"
solana-program-test = "~2.1"
bincode = "1.3.3"

[lib]
crate-type = ["cdylib", "lib"]
